### ISSUE TITLE
Bandwidth Statistics not Updating

### ISSUE THREAD

**Issue by CloudieLLC** [Performave/convoy#14]
Proxmox: 7.3-3
Convoy: v3.6.2-beta

Expected: Bandwidth to update

What it does: it does not update!

Image: 
`https://my.screenimg.xyz/23cebfa6`

Same occurred in Fro's test servers, but wanted to test it on my end as well.

**Comment by as202400** [comment]
It’s work if you manually set the bandwidth usage to 1 or anything but not null.

**Comment by CloudieLLC** [comment]
as i said, it doesn't work in Fro's test servers as well, which does have a limit set :)

https://my.screenimg.xyz/6c8af99d

**Comment by as202400** [comment]
The bandwidth usage(not limit) should be set to 1 manually by the administrator, I wish to say. It will begin counting if the value wasnt NULL or 0; else, it will remain at 0

**Comment by ericwang401** [comment]
> as i said, it doesn't work in Fro's test servers as well, which does have a limit set :)
> 
> https://my.screenimg.xyz/6c8af99d

Bandwidth usage doesn't appear to count because the amount of bandwidth used within a 5 minute period is too low to make up at least 1 mebibyte. Although Convoy displays every data unit in bytes, the panel stores it as integer mebibytes in the database. Consequently, any bandwidth usage that doesn't add up to at least 1 MiB within 5 minutes doesn't get saved because of loss of precision when converting from bytes to mebibytes.

**Comment by ericwang401** [comment]
I will be closing this issue because the impact of this bug is very minimal and may be further remedied in a future update. Because of the precision error, a user can run their server's network at 3.14 kb/s and escape usage logging, which over 30 days racks up 8 gib in usage that's not logged by Convoy. I might increase the period of when Convoy does calculations for logging so that users would have to limit their network speed to 0.001 kb/s to avoid detection. At that point, you can just use dialup instead.

**Comment by ericwang401** [comment]
Fixed in https://github.com/ConvoyPanel/panel/releases/tag/v3.7.1-beta
