### ISSUE TITLE
Feature Request: Add Additional Interface

### ISSUE THREAD

**Issue by CloudieLLC** [Performave/convoy#15]
Would love the ability to add in a secondary interface to clients via the panel.

Use Case: IXP VMs

But, can also be used for private vlans between user servers etc.

**Comment by ericwang401** [comment]
Is it okay if you can elaborate more on the specific implementation of this feature?

**Comment by pafeliepixel** [comment]
Probably the user was referring to the ability to add multiple NICs and see your defined vlans from proxmox(via dropdown menu), or at least be able to type them in :D.

**Comment by ericwang401** [comment]
> Probably the user was referring to the ability to add multiple NICs and see your defined vlans from proxmox(via dropdown menu), or at least be able to type them in :D.

Yes, I am curious in a thought-out implementation (not necessarily in code) that integrates tightly within Convoy's existing features and in a way that can augment other parts of Convoy too.

**Comment by pafeliepixel** [comment]
> > Probably the user was referring to the ability to add multiple NICs and see your defined vlans from proxmox(via dropdown menu), or at least be able to type them in :D.
> 
> Yes, I am curious in a thought-out implementation (not necessarily in code) that integrates tightly within Convoy's existing features and in a way that can augment other parts of Convoy too.

I understand, well, hope the user tell you more then.

I could personally see an advantage to be able to control the network traffic within the panel, multiple nics, vlans and subnets all on the same machine, but that's a sysadmin way of looking at things.

That being said, I think that's not the direction this panel should go, being focused on the end user(and not an admin tool, we have our backend for that-proxmox) which is already mostly covered. Maybe add this options only on the admin side of the panel? Not too complex though.

Since the admin page "still under construction" it could go for some metrics of the node itself, a panel with all the machines, with their status, onwer and OS and maybe there you could add a panel with dropdowns, select machine, add aditional nic and network, with vlan tagging, after the user hits save, revert to blank. But again for this to work, proxmox should be first configured with trunk ports and so on.

Buttom line, there is an idea, but maybe in a distant future, at least from my perspective. You can add the other things to the main admin page though :D.

**Comment by ericwang401** [comment]
This request must be remade with the new feature request template.
