### ISSUE TITLE
Display template UUID's and NodeId's on Convoy.

### ISSUE THREAD

**Issue by ArcheryLuna** [Performave/convoy#40]
Please I dont want to use postman to get the UUID every time.

Pterodactly puts the ID of the nests, nodes and eggs to the left for ease of access at the moment I have to FETCH the ID's and UUID's via the API.

Best wishes
Archery Luna - Seb @ Halvex

**Comment by W1ldAustin** [comment]
Hello Archery Luna,

Please simply code a solution yourself and submit a pull request. 👍

**Comment by yatinmanuel** [comment]
More of a suggestion for enhancement for the end-user utilizing external modules for provisioning (WHMCS module to be specific)

We're perfectly fine with fetching ID/UUIDs for Nodes and Templates via the API, but this would probably be tedious for somebody looking to setup our module, rather than asking them to manually fetch via the API, it would be better to display them in Convoy to keep a useful similarity between Convoy's provisioning module and Pterodactyl's (some elements are derived from Pterodactyl's module)

Thank You

**Comment by ericwang401** [comment]
This has been added in 3e627ef
