### ISSUE TITLE
create lxc servers

### ISSUE THREAD

**Issue by Turkidev** [Performave/convoy#99]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

a button when creating a server if its true show the lxc templates if false show the kvm templates

### Describe the solution you'd like.

.

### Additional context to this request.

.

**Comment by ericwang401** [comment]
Hello, thanks for providing feedback, but LXC support is currently not a priority for Convoy or me (since I'm the only maintainer). I have all my resources focused on the absolute essentials for providing a quality experience in managing KVM servers.

I apologize for the disappointment, but I hope you can understand.
